name: prime_server windows
on: [pull_request]

jobs:
  build:
    name: build and test
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: vcpkg cache
        uses: actions/cache@v4
        with:
          path: C:\vcpkg\installed
          key: vcpkg-windows-x64-${{ hashFiles('.github/workflows/windows.yaml') }}
          restore-keys: vcpkg-windows-x64-

      - name: dependencies
        shell: pwsh
        run: |
          vcpkg install zeromq czmq curl[core]

      - name: build
        shell: pwsh
        run: |
          cmake -B build -S . `
            -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
            -DCMAKE_BUILD_TYPE=RelWithDebInfo `
            -DENABLE_WERROR=Off
          cmake --build build --config RelWithDebInfo -j $env:NUMBER_OF_PROCESSORS

      - name: test
        shell: pwsh
        run: |
          ctest --test-dir build --build-config RelWithDebInfo --output-on-failure -j $env:NUMBER_OF_PROCESSORS
